Resources: change of project data structure
MoonDweller29/vulkan_3d pull request #10
Opened 2020-10-03 14:16 UTC by MoonDweller29

Changes:
- all resources should be stored in subdirectories of data dir;
- cmake creates data dir and symlink to it;
- models and textures are downloaded by cmake from vulkan-tutorial.com

2020-10-03 19:01 UTC, aiosadchy requested changes

2020-10-04 05:36 UTC, MoonDweller29 commented on .gitignore
> +external_libs/*
Её нету, это Алексей случайно закинул сюда, когда добавил в .gitignore папку external

2020-10-04 05:54 UTC, MoonDweller29 commented on .gitignore
> +external_libs/*
удалил

2020-10-04 05:54 UTC, MoonDweller29 commented on CMakeLists.txt
> +set(DATA_LOADING_LOG ${CMAKE_CURRENT_BINARY_DIR}/data_loading.log)
переименовал

2020-10-04 07:02 UTC, aiosadchy submitted a review, later dismissed

2020-10-11 12:21 UTC, Nastormo approved these changes

2020-10-11 12:24 UTC, merged