Models Downloading: added model loading from vulkan-tutorial.com
MoonDweller29/vulkan_3d pull request #5
Opened 2020-09-28 19:11 UTC by MoonDweller29

Now models dir is created by cmake and filled by downloaded files.
Log of downloading op is saved to file models_loading.log.

2020-09-28 21:50 UTC, Nastormo requested changes

2020-09-28 21:50 UTC, Nastormo commented on CMakeLists.txt
> +set(MODELS_DIR ${CMAKE_SOURCE_DIR}/models)
Почему создаешь в CMAKE_SOURCE_DIR а не в CMAKE_CURRENT_BINARY_DIR. Просто тогда путь "../models/*" работает только тогда когда они находятся рядом.

2020-09-28 21:50 UTC, Nastormo commented on CMakeLists.txt
> +# //////////////////////////////////////////////////////
Исходя как написаны другие ограничители тут они не нужны так как есть ниже, но тут дело вкуса видимо

2020-09-29 00:52 UTC, MoonDweller29 commented on CMakeLists.txt
> +set(MODELS_DIR ${CMAKE_SOURCE_DIR}/models)
Чтобы не плодить копии папок с этими ресурсами.
Если прописать создание в CMAKE_CURRENT_BINARY_DIR, тогда у нас на каждый билд будет по копии ресурсов. Что как-то неоч звучит.
Я думаю, мы можем слегка схитрить и сделать файл в CMAKE_CURRENT_BINARY_DIR, который нам будет указывать путь до CMAKE_SOURCE_DIR.
А программа будет читать из этого файла, как из конфига и дальше работать с учётом того, где лежат ресурсы.

2020-09-29 01:04 UTC, aiosadchy commented on CMakeLists.txt
> +set(MODELS_DIR ${CMAKE_SOURCE_DIR}/models)
```
set (source "${CMAKE_SOURCE_DIR}/resources")
set (destination "${CMAKE_CURRENT_BINARY_DIR}/resources")
add_custom_command(
 TARGET ${PROJECT_NAME} POST_BUILD
 COMMAND ${CMAKE_COMMAND} -E create_symlink ${source} ${destination} 
 DEPENDS ${destination}
 COMMENT "symbolic link resources folder from ${source} => ${destination}"
)
```
Примерно так можно сделать

2020-10-03 14:35 UTC, closed without merging