Configuration files
MoonDweller29/vulkan_3d pull request #6
Opened 2020-09-28 22:06 UTC by aiosadchy

Добавил конфиги
Пример использования -- в test_config.cpp
Тест нужно будет переделать, но для этого нужно определиться с тем, как

2020-09-29 10:57 UTC, Nastormo requested changes

2020-09-29 10:57 UTC, Nastormo commented on src/main.cpp
> +    test_config();
Мне чет максимально не нрав что мы тест конфига запихиваем в главный проект. По хорошему это наверное должен быть отдельный тест кейс ну это возможно чисто мое мнение

2020-09-29 21:10 UTC, aiosadchy commented on src/main.cpp
> +    test_config();
Добавил отдельную цель для тестов и убрал это из основного проекта

2020-09-29 23:24 UTC, Nastormo approved these changes

2020-09-30 08:38 UTC, MoonDweller29 commented on src/main.cpp
> -
По-хорошему, изменения пустых строк в коммите не должно быть.
Особенно учитывая то, что мэйн этот коммит вообще не затрагивает.

2020-09-30 08:40 UTC, MoonDweller29 commented on include/app/config/config.h
> +    file << std::setw(4) << jsn;
Я так и не сообразил, зачем тут std::setw?

2020-09-30 09:05 UTC, MoonDweller29 commented on include/app/config/config.h
> +    template <typename T, typename SFINAE>
Что такое SFINAE?

2020-10-01 02:16 UTC, aiosadchy commented on src/main.cpp
> -
Мой косяк, откатил

2020-10-01 02:16 UTC, aiosadchy commented on include/app/config/config.h
> +    file << std::setw(4) << jsn;
Для форматирования: это добавляет отступ в четыре пробела перед каждой новой вложенной секцией

2020-10-01 02:19 UTC, aiosadchy commented on include/app/config/config.h
> +    template <typename T, typename SFINAE>
Как термин: [неплохое описание в вики](https://ru.wikipedia.org/wiki/SFINAE)
В данном контексте это означает, что второй аргумент не используется в шаблонном классе явно, а нужен только для того, чтобы выбрать нужную специализацию шаблона

2020-10-01 08:32 UTC, MoonDweller29 approved these changes
Looks ok, should be merged

2020-10-01 11:03 UTC, merged